[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1
hook_source = '''
    let g:deoplete#enable_at_startup = 1
    let g:deoplete#enable_ignore_case = 1

    if !exists('g:deoplete#omni_patterns')
        let g:deoplete#omni_patterns = {}
    endif

    let g:deoplete#omni_patterns.typescript = '[^. *\t]\.\w*\|\h\w*::'
'''

# [[plugins]]
# if = 'has("nvim")'
# repo = 'mhartington/nvim-typescript'

[[plugins]]
repo = 'zchee/deoplete-go'
if = 'has("nvim")'
on_ft = ['go']
build = 'make'
