[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'Shougo/vimshell.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
    let g:quickrun_config = get(g:, 'quickrun_config', {})

    let g:quickrun_config['_'] = {
    \    'runner' : 'vimproc',
    \    'runner/vimproc/updatetime' : 60,
    \    'outputter/buffer/split' : ':botright 8sp',
    \    'outputter/buffer/close_on_empty' : 1,
    \}

    let g:quickrun_config['tex'] = {
    \    'hook/cd/directory' : '%S:p:h',
    \    'command' : 'latexmk',
    \    'cmdopt' : '-pv',
    \    'srcfile' : '%:p:h:gs?$?/main.tex?',
    \}

    let g:quickrun_config['cpp'] = {
    \    'command' : 'g++',
    \    'cmdopt' : '-std=c++11',
    \}

    let g:quickrun_config['python'] = {
    \    'command' : 'python3',
    \}
'''

[[plugins]]
repo = 'Shougo/vimfiler.vim'
hook_add = '''
    let g:vimfiler_as_default_explorer = 1
    nnoremap <silent> <Leader>f :<C-u>VimFilerExplorer -toggle<CR>

    call vimfiler#custom#profile('default', 'context', {
    \    'safe' : 0,
    \})
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {
    \    'colorscheme': 'wombat',
    \}
'''

[[plugins]]
repo = 'jonathanfilip/vim-lucius'
hook_add = '''
    let g:lucius_style = 'dark'
    let g:lucius_contrast = 'normal'
'''

[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'

[[plugins]]
repo = 'osyo-manga/shabadou.vim'

[[plugins]]
repo = 'cohama/vim-hier'

[[plugins]]
repo = 'cohama/agit.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
    autocmd BufWritePost * GitGutter
'''

[[plugins]]
repo = 'Shougo/neoinclude.vim'
