[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc'

hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif dein#util#_is_mac()
    let cmd = 'make -f make_mac.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'Shougo/vimshell.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
    let g:quickrun_config = {
    \    "_" : {
    \        'runner' : 'vimproc',
    \        'runner/vimproc/updatetime' : 60,
    \        'outputter/buffer/split' : ':botright 8sp',
    \        'outputter/buffer/close_on_empty' : 1,
    \    },
    \}

    let g:quickrun_config['tex'] = {
    \    'hook/cd/directory' : '%S:p:h',
    \    'command' : 'latexmk',
    \    'srcfile' : 'main.tex',
    \    'cmdopt' : '-pv',
    \}

    let g:quickrun_config['cpp'] = {
    \    'command' : 'g++',
    \    'cmdopt' : '-std=c++11',
    \}
'''

# [[plugins]]
# repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'itchyny/lightline.vim'
# hook_add = '''
#     let g:lightline = {
#         \ 'colorscheme': 'solarized',
#         \ }
# '''
