[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1
hook_source = '''
    let g:deoplete#enable_at_startup = 1
    let g:deoplete#enable_ignore_case = 1
'''

[[plugins]]
repo = 'zchee/deoplete-go'
if = 'has("nvim")'
on_ft = ['go']
build = 'make'
