[[plugins]]
repo = 'Shougo/neosnippet'
on_event = 'InsertEnter'
hook_source = '''
    imap <C-k> <Plug>(neosnippet_expand_or_jump)
    smap <C-k> <Plug>(neosnippet_expand_or_jump)
    xmap <C-k> <Plug>(neosnippet_expand_target)

    let g:neosnippet#snippets_directory = '~/.vim/snippets/'
'''

[[plugins]]
repo = 'Shougo/neocomplete'
if = 'has("lua")'
on_event = 'InsertEnter'
hook_source = '''
    let g:neocomplete#enable_at_startup = 1
    let g:neocomplete#enable_ignore_case = 1

    if !exists('g:neocomplete#force_omni_input_patterns')
      let g:neocomplete#force_omni_input_patterns = {}
    endif
    let g:neocomplete#force_overwrite_completefunc = 1
    let g:neocomplete#force_omni_input_patterns.c =
          \ '[^.[:digit:] *\t]\%(\.\|->\)\w*'
    let g:neocomplete#force_omni_input_patterns.cpp =
          \ '[^.[:digit:] *\t]\%(\.\|->\)\w*\|\h\w*::\w*'
    let g:neocomplete#force_omni_input_patterns.typescript =
          \ '[^. *\t]\.\w*\|\h\w*::'
'''

[[plugins]]
repo = 'justmao945/vim-clang'
if = '!has("nvim")'
on_ft = ['c', 'cpp']
hook_source = '''
    let g:clang_auto = 0

    let g:clang_c_options = '-std=c11'
    let g:clang_cpp_options = '-std=c++1z -stdlib=libc++ --pedantic-errors'
    let g:clang_check_syntax_auto = 1

    let g:clang_c_completeopt = 'longest,menuone,preview'
    let g:clang_cpp_completeopt = 'longest,menuone,preview'

    let g:clang_verbose_pmenu = 1
'''


[[plugins]]
repo = 'kannokanno/previm'
on_cmd = 'PrevimOpen'
hook_source = '''
    let g:previm_enable_realtime = 0

    if has('mac')
        let g:previm_open_cmd = 'open -a Firefox'
    endif
'''

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'Quramy/tsuquyomi'
on_ft = ['typescript']

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown']
hook_source = '''
    let g:vim_markdown_folding_disabled = 1
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_add = '''
    let g:go_fmt_command = "goimports"
'''

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = ['pug']
