[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1
hook_source = '''
    let g:deoplete#enable_at_startup = 1
    let g:deoplete#enable_ignore_case = 1

    if !exists('g:deoplete#omni_patterns')
        let g:deoplete#omni_patterns = {}
    endif

    let g:deoplete#omni_patterns.typescript = '[^. *\t]\.\w*\|\h\w*::'
'''

# [[plugins]]
# if = 'has("nvim")'
# repo = 'mhartington/nvim-typescript'

[[plugins]]
repo = 'zchee/deoplete-go'
if = 'has("nvim")'
on_ft = ['go']
build = 'make'

[[plugins]]
repo = 'zchee/deoplete-clang'
if = 'has("nvim")'
on_ft = ['c', 'cpp']
depends = ['deoplete.nvim']
hook_source = '''
    if has('unix')
        let g:deoplete#sources#clang#libclang_path = '/usr/lib/llvm-3.8/lib/libclang.so'
        let g:deoplete#sources#clang#clang_header = '/usr/include/clang/'
        let g:deoplete#sources#clang#sort_algo = 'alphabetical'
    endif
'''

# [[plugins]]
# repo = 'davidhalter/jedi-vim'

[[plugins]]
repo = 'zchee/deoplete-jedi'
