" Window
" 縦幅　デフォルトは24
set lines=40
" 横幅　デフォルトは80
set columns=120

" Input
" set imdisable

" Display
" カラースキーマの設定をluciusにする
colorscheme lucius
" フォントを変更する
set guifont=Meiryo_Consolas:h12
set guifontwide=Meiryo_Consolas:h12
" アンダーラインを引く(gui)
" highlight CursorLine guibg=#1f1f1f

" Disable beeping
set visualbell t_vb=
