if &compatible
    set nocompatible
endif

function! s:source_rc(file_name) abort
    let path = expand('~/.vim/rc/' . a:file_name)
    execute 'source ' . path
endfunction

if has('vim_starting')
    call s:source_rc('init.vim')
endif

call s:source_rc('dein.vim')
call s:source_rc('mappings.vim')
call s:source_rc('basic.vim')
call s:source_rc('view.vim')

filetype plugin indent on
