name: benchmark

on:
  push:
    branches:
      - master

permissions:
  deployments: write
  contents: write

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Install test dependencies
        if: runner.os == 'linux'
        run: |
          sudo apt update
          sudo apt install zsh

          # Install hyperfine
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.14.0/hyperfine_1.14.0_amd64.deb
          sudo dpkg -i hyperfine_1.14.0_amd64.deb

      - name: Install test dependencies
        if: runner.os == 'macos'
        run: brew install zsh hyperfine

      - name: Install dotfiles
        run: make link

      - name: Run benchmark
        run: |
          ./scripts/benchmark.sh > result.json
          cat result.json

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: "customSmallerIsBetter"
          output-file-path: result.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
