name: linux-test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Cache asdf
        uses: actions/cache@v3
        with:
          path: ~/.asdf
          key: ${{ runner.os }}-asdf-${{ hashFiles('./etc/installer/asdf.sh', '~/.tool-versions') }}

      - name: Cache .venv
        uses: actions/cache@v3
        with:
          path: ~/.venv
          key: ${{ runner.os }}-asdf-${{ hashFiles('./etc/installer/venv.sh', '~/.tool-versions') }}

      - name: Install dotfiles
        run: make init
