name: test

on:
  push:
    branches:
      - master

permissions:
  deployments: write
  contents: write

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-12]
    timeout-minutes: 10

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Cache asdf
        uses: actions/cache@v3
        with:
          path: ~/.asdf
          key: ${{ runner.os }}-asdf-${{ hashFiles('./etc/installer/asdf.sh', '.tool-versions') }}

      - name: Cache venv
        uses: actions/cache@v3
        with:
          path: ~/.venv
          key: ${{ runner.os }}-asdf-${{ hashFiles('./etc/installer/venv.sh', '.tool-versions') }}

      - name: Install test dependencies
        if: runner.os == 'linux'
        run: |
          sudo apt update
          sudo apt install zsh

          # Install hyperfine
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.14.0/hyperfine_1.14.0_amd64.deb
          sudo dpkg -i hyperfine_1.14.0_amd64.deb

      - name: Install test dependencies
        if: runner.os == 'macos'
        run: brew install zsh hyperfine

      - name: Install dotfiles
        run: make init

      - name: Run zsh benchmark
        shell: zsh
        run: |
          ./scripts/benchmark.sh 'zsh -i -c exit' 'zsh load time (${{ runner.os }})' > zsh-benchmark-result.json
          cat zsh-benchmark-result.json

      - name: Run neovim benchmark
        shell: zsh
        run: |
          ./scripts/benchmark.sh 'nvim --headless -c q' 'nvim load time (${{ runner.os }})' > nvim-benchmark-result.json
          cat nvim-benchmark-result.json

      - name: Store zsh benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Zsh Benchmark
          tool: "customSmallerIsBetter"
          output-file-path: zsh-benchmark-result.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true

      - name: Store neovim benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Neovim Benchmark
          tool: "customSmallerIsBetter"
          output-file-path: nvim-benchmark-result.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
